### PR TITLE
setuptools compliancy

### PR DESCRIPTION
**Pull request by hootnot**
make the _oandapy_  _setuptools_ compliant. This makes it __pip__ installable. Optionally the package could be put on _pypi.python.org_

versioning up to OANDA, I guess semantic versioning MAJOR.MINOR.PATCH would be the way to go.

Please, see request #9 and #20 also.

After this change installing and upgrading comes down to:
__pip__ install git+https://github.com/oanda/oandapy

a _pypi_ package would even be more convenient:
__pip__ install oandapy

### CODE REVIEW

**Comment by alekna** [comment]
Doesn't work with Python 3:
```
[root@380065207cac /]# python3
Python 3.4.3 (default, Jun 29 2015, 12:16:01) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import oandapy 
>>> oandapy.API()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'API'
>>> 
```

Work fine with Python 2:
```
[root@380065207cac /]# python
Python 2.7.10 (default, Sep  8 2015, 17:20:17) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import oandapy
>>> oandapy.API()
<oandapy.oandapy.API object at 0x7f18d3dbf2d0>
>>> 
```

**Comment by hootnot** [comment]
Hi,

if you modify oandapy/__init__.py

--- a/oandapy/__init__.py
+++ b/oandapy/__init__.py
@@ -1 +1 @@
-from oandapy import *
+from .oandapy import *

is is solved


2016-01-25 17:16 GMT+01:00 Laurynas Alekna <notifications@github.com>:

> Doesn't work with Python 3:
>
> [root@380065207cac /]# python3
> Python 3.4.3 (default, Jun 29 2015, 12:16:01)
> [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import oandapy
> >>> oandapy.API()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'module' object has no attribute 'API'
> >>>
>
> Work fine with Python 2:
>
> [root@380065207cac /]# python
> Python 2.7.10 (default, Sep  8 2015, 17:20:17)
> [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import oandapy
> >>> oandapy.API()
> <oandapy.oandapy.API object at 0x7f18d3dbf2d0>
> >>>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oanda/oandapy/pull/21#issuecomment-174559260>.
>



-- 
Feite Brekeveld

feitebrekeveld <https://nl.linkedin.com/in/feitebrekeveld>
@feite_brekeveld <https://twitter.com/feite_brekeveld>
github <https://github.com/hootnot>

**Comment by alekna** [comment]
It helped. Will you create another PR?

**Comment by hootnot** [comment]
I've made the change and pushed it. It is in the pending pull request I
made the 19th.

2016-01-25 17:57 GMT+01:00 Laurynas Alekna <notifications@github.com>:

> It helped. Will you create another PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oanda/oandapy/pull/21#issuecomment-174581553>.
>



-- 
Feite Brekeveld

feitebrekeveld <https://nl.linkedin.com/in/feitebrekeveld>
@feite_brekeveld <https://twitter.com/feite_brekeveld>
github <https://github.com/hootnot>

**Comment by hootnot** [comment]
I have written some tests to test the complete API. Tests pass Python
2.7.5. I will see to test Python 3 also.

Regards,
Feite

2016-01-25 17:16 GMT+01:00 Laurynas Alekna <notifications@github.com>:

> Doesn't work with Python 3:
>
> [root@380065207cac /]# python3
> Python 3.4.3 (default, Jun 29 2015, 12:16:01)
> [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import oandapy
> >>> oandapy.API()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'module' object has no attribute 'API'
> >>>
>
> Work fine with Python 2:
>
> [root@380065207cac /]# python
> Python 2.7.10 (default, Sep  8 2015, 17:20:17)
> [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import oandapy
> >>> oandapy.API()
> <oandapy.oandapy.API object at 0x7f18d3dbf2d0>
> >>>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oanda/oandapy/pull/21#issuecomment-174559260>.
>



-- 
Feite Brekeveld

feitebrekeveld <https://nl.linkedin.com/in/feitebrekeveld>
@feite_brekeveld <https://twitter.com/feite_brekeveld>
github <https://github.com/hootnot>

**Comment by alekna** [comment]
Why don't you split your changes into multiple branches/PRs ? Putting it all under name of "Update of README" is a bit misinforming.

**Comment by hootnot** [comment]
Yes you are right and I've noticed it too. Therefore I've already made a
branche  for the extension of the Streamer class and will make the PR's
from there. I will do so for the testcode too.

2016-01-25 18:16 GMT+01:00 Laurynas Alekna <notifications@github.com>:

> Why don't you split your changes into multiple branches/PRs ? Putting it
> all under name of "Update of README" is a bit misinforming.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oanda/oandapy/pull/21#issuecomment-174590327>.
>



-- 
Feite Brekeveld

feitebrekeveld <https://nl.linkedin.com/in/feitebrekeveld>
@feite_brekeveld <https://twitter.com/feite_brekeveld>
github <https://github.com/hootnot>

**Comment by alekna** [comment]
Good luck. I hope they will accept your changes/improvements. They're not very good at this. As if no one at OANDA cares about API anymore.

**Pull request merged**
